### ISSUE TITLE
调用 task.cancel() tmp 文件没有删除干净

### ISSUE THREAD

**Issue by Mob0x64** [PorridgeKiller/node-parallel-downloader#2]
创建下载任务会生产如下目录结构：
```
taskId-20200816171240
  |- chunk_20200816171240_1.tmp
  |- chunk_20200816171240_2.tmp
taskId_chunk_20200816171250_0.tmp
```

调用 **task.cancel()** 后 **taskId_chunk_20200816171250_0.tmp** 未被删除

**Comment by PorridgeKiller** [comment]
感谢反馈。是下载中调用吗，可不可以更具体描述下场景，我好排查一下。

**Comment by Mob0x64** [comment]
> 感谢反馈。是下载中调用吗，可不可以更具体描述下场景，我好排查一下。

下载和暂停的情况下都会，chunk0 不会被删除
对于正在下载和暂停情况下的任务，我是直接用 taskGroup 创建一个 task 来调用 cancel 方法进行任务的取消（新创建的 task 的 taskId 和已存在的 task 是一样的）

**Comment by PorridgeKiller** [comment]
> > 感谢反馈。是下载中调用吗，可不可以更具体描述下场景，我好排查一下。
> 
> 下载和暂停的情况下都会，chunk0 不会被删除
> 对于正在下载和暂停情况下的任务，我是直接用 taskGroup 创建一个 task 来调用 cancel 方法进行任务的取消（新创建的 task 的 taskId 和已存在的 task 是一样的）

我这边无论怎么调试都没有出现删不掉的情况，看了下你给的目录结构，chunk0是20200816171250后缀，其他的都是20200816171240后缀，是不是20200816171250后缀的是其他任务的chunk所以删不掉。同一个任务锁创建的所有目录和chunk文件后缀都会是同样的时间戳的。

**Comment by Mob0x64** [comment]
> > > 感谢反馈。是下载中调用吗，可不可以更具体描述下场景，我好排查一下。
> > 
> > 
> > 下载和暂停的情况下都会，chunk0 不会被删除
> > 对于正在下载和暂停情况下的任务，我是直接用 taskGroup 创建一个 task 来调用 cancel 方法进行任务的取消（新创建的 task 的 taskId 和已存在的 task 是一样的）
> 
> 我这边无论怎么调试都没有出现删不掉的情况，看了下你给的目录结构，chunk0是20200816171250后缀，其他的都是20200816171240后缀，是不是20200816171250后缀的是其他任务的chunk所以删不掉。同一个任务锁创建的所有目录和chunk文件后缀都会是同样的时间戳的。

我再检查了一边，上面给的目录时间我复制错了，删不掉的 chunk0 的时间和文件夹的时间戳是一样的。
我的系统是 macOS Big Sur，可能和系统有关？
还有我想问下，把 chunk0 单独放在文件夹外的原因是什么？

**Comment by Mob0x64** [comment]
> > > 感谢反馈。是下载中调用吗，可不可以更具体描述下场景，我好排查一下。
> > 
> > 
> > 下载和暂停的情况下都会，chunk0 不会被删除
> > 对于正在下载和暂停情况下的任务，我是直接用 taskGroup 创建一个 task 来调用 cancel 方法进行任务的取消（新创建的 task 的 taskId 和已存在的 task 是一样的）
> 
> 我这边无论怎么调试都没有出现删不掉的情况，看了下你给的目录结构，chunk0是20200816171250后缀，其他的都是20200816171240后缀，是不是20200816171250后缀的是其他任务的chunk所以删不掉。同一个任务锁创建的所有目录和chunk文件后缀都会是同样的时间戳的。

我再检查了一遍，上面给的目录时间我复制错了，删不掉的 chunk0 的时间和文件夹的时间戳是一样的。
我的系统是 macOS Big Sur，可能和系统有关？
还有我想问下，把 chunk0 单独放在文件夹外的原因是什么？

**Comment by Mob0x64** [comment]
> > > 感谢反馈。是下载中调用吗，可不可以更具体描述下场景，我好排查一下。
> > 
> > 
> > 下载和暂停的情况下都会，chunk0 不会被删除
> > 对于正在下载和暂停情况下的任务，我是直接用 taskGroup 创建一个 task 来调用 cancel 方法进行任务的取消（新创建的 task 的 taskId 和已存在的 task 是一样的）
> 
> 我这边无论怎么调试都没有出现删不掉的情况，看了下你给的目录结构，chunk0是20200816171250后缀，其他的都是20200816171240后缀，是不是20200816171250后缀的是其他任务的chunk所以删不掉。同一个任务锁创建的所有目录和chunk文件后缀都会是同样的时间戳的。

我检查了一下，20200816171240 和 20200816171250 不一致是我复制错了，抱歉。
我重新创建了一个下载任务，发现 chunk0 确实不会在 cancel 之后被删除。反倒会删除文件名为 descriptor.filename 的文件。
我看了下源码，发现 task.cancel 时会删除 downloadDir 和 outputFilePath，这个 outputFilePath 是 FileOperator.pathJoin(descriptor.storageDir, descriptor.filename) 的返回值。
我在源码中没有没有找到删除 chunk0 的代码。您看看，是不是我哪里理解错了。

**Comment by PorridgeKiller** [comment]
> > > > 感谢反馈。是下载中调用吗，可不可以更具体描述下场景，我好排查一下。
> > > 
> > > 
> > > 下载和暂停的情况下都会，chunk0 不会被删除
> > > 对于正在下载和暂停情况下的任务，我是直接用 taskGroup 创建一个 task 来调用 cancel 方法进行任务的取消（新创建的 task 的 taskId 和已存在的 task 是一样的）
> > 
> > 
> > 我这边无论怎么调试都没有出现删不掉的情况，看了下你给的目录结构，chunk0是20200816171250后缀，其他的都是20200816171240后缀，是不是20200816171250后缀的是其他任务的chunk所以删不掉。同一个任务锁创建的所有目录和chunk文件后缀都会是同样的时间戳的。
> 
> 我检查了一下，20200816171240 和 20200816171250 不一致是我复制错了，抱歉。
> 我重新创建了一个下载任务，发现 chunk0 确实不会在 cancel 之后被删除。反倒会删除文件名为 descriptor.filename 的文件。
> 我看了下源码，发现 task.cancel 时会删除 downloadDir 和 outputFilePath，这个 outputFilePath 是 FileOperator.pathJoin(descriptor.storageDir, descriptor.filename) 的返回值。
> 我在源码中没有没有找到删除 chunk0 的代码。您看看，是不是我哪里理解错了。

你的下载链接是多少，可以贴出来让我调试一下吗

**Comment by PorridgeKiller** [comment]
> > > > 感谢反馈。是下载中调用吗，可不可以更具体描述下场景，我好排查一下。
> > > 
> > > 
> > > 下载和暂停的情况下都会，chunk0 不会被删除
> > > 对于正在下载和暂停情况下的任务，我是直接用 taskGroup 创建一个 task 来调用 cancel 方法进行任务的取消（新创建的 task 的 taskId 和已存在的 task 是一样的）
> > 
> > 
> > 我这边无论怎么调试都没有出现删不掉的情况，看了下你给的目录结构，chunk0是20200816171250后缀，其他的都是20200816171240后缀，是不是20200816171250后缀的是其他任务的chunk所以删不掉。同一个任务锁创建的所有目录和chunk文件后缀都会是同样的时间戳的。
> 
> 我检查了一下，20200816171240 和 20200816171250 不一致是我复制错了，抱歉。
> 我重新创建了一个下载任务，发现 chunk0 确实不会在 cancel 之后被删除。反倒会删除文件名为 descriptor.filename 的文件。
> 我看了下源码，发现 task.cancel 时会删除 downloadDir 和 outputFilePath，这个 outputFilePath 是 FileOperator.pathJoin(descriptor.storageDir, descriptor.filename) 的返回值。
> 我在源码中没有没有找到删除 chunk0 的代码。您看看，是不是我哪里理解错了。

我各种方法试了好多遍，没有复现你描述的情况，是不是用的1.0.45版本，换最新的试一试看看可不可以。

**Comment by Mob0x64** [comment]
> > > > > 感谢反馈。是下载中调用吗，可不可以更具体描述下场景，我好排查一下。
> > > > 
> > > > 
> > > > 下载和暂停的情况下都会，chunk0 不会被删除
> > > > 对于正在下载和暂停情况下的任务，我是直接用 taskGroup 创建一个 task 来调用 cancel 方法进行任务的取消（新创建的 task 的 taskId 和已存在的 task 是一样的）
> > > 
> > > 
> > > 我这边无论怎么调试都没有出现删不掉的情况，看了下你给的目录结构，chunk0是20200816171250后缀，其他的都是20200816171240后缀，是不是20200816171250后缀的是其他任务的chunk所以删不掉。同一个任务锁创建的所有目录和chunk文件后缀都会是同样的时间戳的。
> > 
> > 
> > 我检查了一下，20200816171240 和 20200816171250 不一致是我复制错了，抱歉。
> > 我重新创建了一个下载任务，发现 chunk0 确实不会在 cancel 之后被删除。反倒会删除文件名为 descriptor.filename 的文件。
> > 我看了下源码，发现 task.cancel 时会删除 downloadDir 和 outputFilePath，这个 outputFilePath 是 FileOperator.pathJoin(descriptor.storageDir, descriptor.filename) 的返回值。
> > 我在源码中没有没有找到删除 chunk0 的代码。您看看，是不是我哪里理解错了。
> 
> 我各种方法试了好多遍，没有复现你描述的情况，是不是用的1.0.45版本，换最新的试一试看看可不可以。

我找到复现的方法了:

1.创建 taskGroup1，创建一个下载任务 task1，启动 task1
2.等待一会儿让 chunk 创建
3.创建 taskGroup2，创建一个下载任务 task2（task2 的 taskId 和 task1 的一致，所以 task2 和 task1 应该是一样的）。调用  task1.stop 停止 task1，调用 task2.cancel 取消下载任务

您试试看能不能复现。如果是不同的 taskGroup 就会出现。taskGroup 创建的时候调用了 loadFromConfigDir 了，所以我认为 taskGroup1 和 taskGropu2 应该是一样的。

**Comment by PorridgeKiller** [comment]
> > > > > > 感谢反馈。是下载中调用吗，可不可以更具体描述下场景，我好排查一下。
> > > > > 
> > > > > 
> > > > > 下载和暂停的情况下都会，chunk0 不会被删除
> > > > > 对于正在下载和暂停情况下的任务，我是直接用 taskGroup 创建一个 task 来调用 cancel 方法进行任务的取消（新创建的 task 的 taskId 和已存在的 task 是一样的）
> > > > 
> > > > 
> > > > 我这边无论怎么调试都没有出现删不掉的情况，看了下你给的目录结构，chunk0是20200816171250后缀，其他的都是20200816171240后缀，是不是20200816171250后缀的是其他任务的chunk所以删不掉。同一个任务锁创建的所有目录和chunk文件后缀都会是同样的时间戳的。
> > > 
> > > 
> > > 我检查了一下，20200816171240 和 20200816171250 不一致是我复制错了，抱歉。
> > > 我重新创建了一个下载任务，发现 chunk0 确实不会在 cancel 之后被删除。反倒会删除文件名为 descriptor.filename 的文件。
> > > 我看了下源码，发现 task.cancel 时会删除 downloadDir 和 outputFilePath，这个 outputFilePath 是 FileOperator.pathJoin(descriptor.storageDir, descriptor.filename) 的返回值。
> > > 我在源码中没有没有找到删除 chunk0 的代码。您看看，是不是我哪里理解错了。
> > 
> > 
> > 我各种方法试了好多遍，没有复现你描述的情况，是不是用的1.0.45版本，换最新的试一试看看可不可以。
> 
> 我找到复现的方法了:
> 
> 1.创建 taskGroup1，创建一个下载任务 task1，启动 task1
> 2.等待一会儿让 chunk 创建
> 3.创建 taskGroup2，创建一个下载任务 task2（task2 的 taskId 和 task1 的一致，所以 task2 和 task1 应该是一样的）。调用 task1.stop 停止 task1，调用 task2.cancel 取消下载任务
> 
> 您试试看能不能复现。如果是不同的 taskGroup 就会出现。taskGroup 创建的时候调用了 loadFromConfigDir 了，所以我认为 taskGroup1 和 taskGropu2 应该是一样的。

感谢你发现这个问题。一个DownloadTaskGroup是支持多个任务并行下载的。从设计理念上来说，这个下载器的DownloadTaskGroup是跟目录绑定的，最好的方式是一个DownloadTaskGroup的元数据文件（.down.json）存储目录对应一个ConfigDir目录，如果需要多个DownloadTaskGroup的元数据文件（.down.json）存储目录都指向同一个ConfigDir，在编码时候就需要给DownloadTaskGroup一个id，否则在运行时是没办法知道哪个.down.json文件属于哪个Group的。这方面的使用方式我没有在文档中描述清楚，稍后我会补全。

**Comment by Mob0x64** [comment]
> > > > > > > 感谢反馈。是下载中调用吗，可不可以更具体描述下场景，我好排查一下。
> > > > > > 
> > > > > > 
> > > > > > 下载和暂停的情况下都会，chunk0 不会被删除
> > > > > > 对于正在下载和暂停情况下的任务，我是直接用 taskGroup 创建一个 task 来调用 cancel 方法进行任务的取消（新创建的 task 的 taskId 和已存在的 task 是一样的）
> > > > > 
> > > > > 
> > > > > 我这边无论怎么调试都没有出现删不掉的情况，看了下你给的目录结构，chunk0是20200816171250后缀，其他的都是20200816171240后缀，是不是20200816171250后缀的是其他任务的chunk所以删不掉。同一个任务锁创建的所有目录和chunk文件后缀都会是同样的时间戳的。
> > > > 
> > > > 
> > > > 我检查了一下，20200816171240 和 20200816171250 不一致是我复制错了，抱歉。
> > > > 我重新创建了一个下载任务，发现 chunk0 确实不会在 cancel 之后被删除。反倒会删除文件名为 descriptor.filename 的文件。
> > > > 我看了下源码，发现 task.cancel 时会删除 downloadDir 和 outputFilePath，这个 outputFilePath 是 FileOperator.pathJoin(descriptor.storageDir, descriptor.filename) 的返回值。
> > > > 我在源码中没有没有找到删除 chunk0 的代码。您看看，是不是我哪里理解错了。
> > > 
> > > 
> > > 我各种方法试了好多遍，没有复现你描述的情况，是不是用的1.0.45版本，换最新的试一试看看可不可以。
> > 
> > 
> > 我找到复现的方法了:
> > 1.创建 taskGroup1，创建一个下载任务 task1，启动 task1
> > 2.等待一会儿让 chunk 创建
> > 3.创建 taskGroup2，创建一个下载任务 task2（task2 的 taskId 和 task1 的一致，所以 task2 和 task1 应该是一样的）。调用 task1.stop 停止 task1，调用 task2.cancel 取消下载任务
> > 您试试看能不能复现。如果是不同的 taskGroup 就会出现。taskGroup 创建的时候调用了 loadFromConfigDir 了，所以我认为 taskGroup1 和 taskGropu2 应该是一样的。
> 
> 感谢你发现这个问题。一个DownloadTaskGroup是支持多个任务并行下载的。从设计理念上来说，这个下载器的DownloadTaskGroup是跟目录绑定的，最好的方式是一个DownloadTaskGroup的元数据文件（.down.json）存储目录对应一个ConfigDir目录，如果需要多个DownloadTaskGroup的元数据文件（.down.json）存储目录都指向同一个ConfigDir，在编码时候就需要给DownloadTaskGroup一个id，否则在运行时是没办法知道哪个.down.json文件属于哪个Group的。这方面的使用方式我没有在文档中描述清楚，稍后我会补全。

其实正常使用一个 Group 就够了，但是由于现在 taskId 是通过绑定在 Group 上的 TaskIdGenerator 来生成的，这样的方式某些情况下难以唯一的定位到一个下载任务，所以我才通过创建多个 Group 的方式来实现需求。downloadUrl、filename、storageDir 其实对于定位一个下载任务来说有点不够。后期会考虑提供在创建 task 的时候由用户直接传入 taskId 的接口吗？

最后谢谢您对这个问题的跟进，辛苦了～

**Comment by PorridgeKiller** [comment]
@Mob0x64 前面的回复引用太长了，就直接发这里。

现在是支持这种方式的。这个下载器是我在开发公司项目中编写的一个模块，为业务提供下载功能，在业务中我也是向你这样使用的，需要关注一下 `DownloadTaskGroup.configTaskIdGenerator(idGenerator: TaskIdGenerator)`方法，是有四个参数的，可以利用最后一个 `attachment` 参数传你的业务参数
````typescript
declare type TaskIdGenerator = (downloadUrl: string, storageDir: string, filename: string | undefined, attachment?: any) => Promise<string>;
````
在创建task的时候传入第四个参数 `attachment`, 这四个参数会作为TaskIdGenerator的参数
```typescript
await group.newTask(
    game.downloadUrl,
    gameInstallDir,
    cacheFilename,
    {
      gameId: game.gameId
    }
);
```
在传进去的taskId生成函数中直接返回你指定的id即可
```typescript
// 创建DownloadTaskGroup
const gameDownGroup = await new DownloadTaskGroup()
    .configHttpTimeout(30000)
    .configRetryTimes(100)
    .configTaskIdGenerator(async (url, storageDir, filename, attachment) => {
        // 这里返回你之前设置的业务id
        return attachment.gameId;
    })
    .configHttpRequestOptionsBuilder((requestOptions, taskId: string, index: number, from: number, to: number, progress: number) => {
        return requestOptions;
     })
    .configFileInfoDescriptor(requestMethodHeadFileInformationDescriptor)
    .configConfigDir(FileUtils.concatToPath(await GameManager.GetInstance().GetGameCacheDir(), 'GameDownloadCache'))
    .configProgressTicktockMillis(2000)
    .configMaxWorkerCount(2)
    .loadFromConfigDir();
```
希望能帮到你

**Comment by Mob0x64** [comment]
> @Mob0x64 前面的回复引用太长了，就直接发这里。
> 
> 现在是支持这种方式的。这个下载器是我在开发公司项目中编写的一个模块，为业务提供下载功能，在业务中我也是向你这样使用的，需要关注一下 `DownloadTaskGroup.configTaskIdGenerator(idGenerator: TaskIdGenerator)`方法，是有四个参数的，可以利用最后一个 `attachment` 参数传你的业务参数
> 
> ```ts
> declare type TaskIdGenerator = (downloadUrl: string, storageDir: string, filename: string | undefined, attachment?: any) => Promise<string>;
> ```
> 
> 在创建task的时候传入第四个参数 `attachment`, 这四个参数会作为TaskIdGenerator的参数
> 
> ```ts
> await group.newTask(
>     game.downloadUrl,
>     gameInstallDir,
>     cacheFilename,
>     {
>       gameId: game.gameId
>     }
> );
> ```
> 
> 在传进去的taskId生成函数中直接返回你指定的id即可
> 
> ```ts
> // 创建DownloadTaskGroup
> const gameDownGroup = await new DownloadTaskGroup()
>     .configHttpTimeout(30000)
>     .configRetryTimes(100)
>     .configTaskIdGenerator(async (url, storageDir, filename, attachment) => {
>         // 这里返回你之前设置的业务id
>         return attachment.gameId;
>     })
>     .configHttpRequestOptionsBuilder((requestOptions, taskId: string, index: number, from: number, to: number, progress: number) => {
>         return requestOptions;
>      })
>     .configFileInfoDescriptor(requestMethodHeadFileInformationDescriptor)
>     .configConfigDir(FileUtils.concatToPath(await GameManager.GetInstance().GetGameCacheDir(), 'GameDownloadCache'))
>     .configProgressTicktockMillis(2000)
>     .configMaxWorkerCount(2)
>     .loadFromConfigDir();
> ```
> 
> 希望能帮到你

太感谢你了！尝试了一下，现在只需要一个 TaskGroup 我就可以实现我的需求了。
