### ISSUE TITLE
如何更新 task 的 downloadUrl

### ISSUE THREAD

**Issue by Mob0x64** [PorridgeKiller/node-parallel-downloader#3]
场景： 
有的下载链接会过期，这就意味着断点续传时会出现下载失败的情况。
如果此时可以更新下载链接，则可以继续进行下载。

**Comment by PorridgeKiller** [comment]
这个有点不好办哦，URL变了的话，一般意味着对应资源变了，断点续传不合适的

**Comment by Mob0x64** [comment]
> 这个有点不好办哦，URL变了的话，一般意味着对应资源变了，断点续传不合适的

我现在直接修改 descriptor 的 downloadUrl 来实现我的需求了（虽然不太合适）不过确实有用 XD
做法就是在 task.start 之前修改 downloadUrl，等于直接架空了 node-parallel-downloader 配置文件中的 downloadUrl 。这样我就可以在资源服务器返回 403 的时候重新获取同一文件的新的下载链接，实现断点续传。

**Comment by Mob0x64** [comment]
> 这个有点不好办哦，URL变了的话，一般意味着对应资源变了，断点续传不合适的

其实还是有些场景会需要更新 downloadUrl 的（例如下载链接失效，有的资源服务器半个小时下载链接就失效了），这时候如果不更新 downloadUrl 那么断点续传必然失败。
个人认为 downloadUrl 只是一个资源标识符，只要新的 downloadUrl 还是指向同一个资源，那么下载就可以正常进行下去。

**Comment by Mob0x64** [comment]
就是因为这个需求（downloadUrl 不同，但是对应的资源还是同一个）所以我没办法使用 TaskIdGenerator 的方式生成 taskId，因为 configTaskIdGenerator 给的参数只有 (downloadUrl, storageDir, filename)，这三个参数没法唯一定位到一个下载任务。我现在只能每次下载都创建一个 taskGroup 了。所以我想是不是能够给一个接口，在创建 task 的时候直接指定 taskId，而不是只能在 taskGroup 中配置生成方式，这样可能会更加灵活一点。
